// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6MMuSVzIURyBC87Jnxh9wvxctNhboyMY',
    appId: '1:95545725777:web:e68ae7fd54ec7f6d033970',
    messagingSenderId: '95545725777',
    projectId: 'mirastec-a1c34',
    authDomain: 'mirastec-a1c34.firebaseapp.com',
    storageBucket: 'mirastec-a1c34.firebasestorage.app',
    measurementId: 'G-W62EPBNTEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp5TmiChWYZM0BMXqYdLKyiA_DJkJEG3Q',
    appId: '1:95545725777:android:622c3817ec31d77b033970',
    messagingSenderId: '95545725777',
    projectId: 'mirastec-a1c34',
    storageBucket: 'mirastec-a1c34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFd7yxWdGO-zbNfmc72Q3oHOpWMjb8AE',
    appId: '1:95545725777:ios:46c248896e1ce586033970',
    messagingSenderId: '95545725777',
    projectId: 'mirastec-a1c34',
    storageBucket: 'mirastec-a1c34.firebasestorage.app',
    iosBundleId: 'com.mirastec.mirastec',
  );
}
